/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author HECTOR MAURICIO
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmeReportes = new javax.swing.JMenu();
        jmiPersonas = new javax.swing.JMenuItem();
        jmiUsuarios = new javax.swing.JMenuItem();
        jmlRegistros = new javax.swing.JMenu();
        jmiVentana1 = new javax.swing.JMenuItem();
        jmiVentana2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpEscritorio.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        jmeReportes.setText("Reportes");

        jmiPersonas.setText("Personas");
        jmiPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPersonasActionPerformed(evt);
            }
        });
        jmeReportes.add(jmiPersonas);

        jmiUsuarios.setText("Usuarios");
        jmiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuariosActionPerformed(evt);
            }
        });
        jmeReportes.add(jmiUsuarios);

        jMenuBar1.add(jmeReportes);

        jmlRegistros.setText("Registros");

        jmiVentana1.setText("jmiVentana1");
        jmiVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVentana1ActionPerformed(evt);
            }
        });
        jmlRegistros.add(jmiVentana1);

        jmiVentana2.setText("jmiVentana2");
        jmiVentana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVentana2ActionPerformed(evt);
            }
        });
        jmlRegistros.add(jmiVentana2);

        jMenuBar1.add(jmlRegistros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPersonasActionPerformed
        // TODO add your handling code here:
        //Instancia de JEnternalFrame Personas
        jtfTablaPersonas tabla = new jtfTablaPersonas();
        //Se incorpora la venta al escritorio
        jdpEscritorio.add(tabla);
        //Se muestra la ventana dentro del escritorio
        tabla.show();
        
    }//GEN-LAST:event_jmiPersonasActionPerformed

    private void jmiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuariosActionPerformed
        // TODO add your handling code here:
        //Instancia de JEnternalFrame Usuarios
        jtfUsuarios usuarios = new jtfUsuarios();
        //Se incorpora la venta al escritorio
        jdpEscritorio.add(usuarios);
        //Se muestra la ventana dentro del escritorio
        usuarios.show();
    }//GEN-LAST:event_jmiUsuariosActionPerformed

    private void jmiVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVentana1ActionPerformed
        // TODO add your handling code here:
        //Instancia de JEnternalFrame Ventana1
        jtfVentana1 v1 = new jtfVentana1();
        //Se incorpora la venta al escritorio
        jdpEscritorio.add(v1);
        //Se muestra la ventana dentro del escritorio
        v1.show();
    }//GEN-LAST:event_jmiVentana1ActionPerformed

    private void jmiVentana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVentana2ActionPerformed
        // TODO add your handling code here:
        //Instancia de JEnternalFrame Ventana1
        jtfVentana2 v2 = new jtfVentana2();
         //Se incorpora la venta al escritorio
        jdpEscritorio.add(v2);
        //Se muestra la ventana dentro del escritorio
        v2.show();
    }//GEN-LAST:event_jmiVentana2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmeReportes;
    private javax.swing.JMenuItem jmiPersonas;
    private javax.swing.JMenuItem jmiUsuarios;
    private javax.swing.JMenuItem jmiVentana1;
    private javax.swing.JMenuItem jmiVentana2;
    private javax.swing.JMenu jmlRegistros;
    // End of variables declaration//GEN-END:variables
}
